env:
  # The version to build. Artifacts will be stored in the cache
  # so that they can be downloaded from Travis' UI.

  - VERSION=0.9.0

language: scala

osx_image: xcode8.3

scala:
  - 2.11.11

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers

before_cache:
  - rm -rf "$HOME/.ivy2/cache/com/lightbend/rp/reactivecli"
  - find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -delete

os: osx

script:
  - ./build-mac-osx
