#!/usr/bin/env bash

set -e

brew install bdw-gc re2 jq sbt
brew install curl --with-openssl

PROJECT=https://github.com/lightbend/reactive-cli

if [ -z "$VERSION" ]; then
  echo "missing env var: VERSION"
  exit 1
fi

echo "* building $VERSION"
pwd

git clone "$PROJECT" reactive-cli

cd reactive-cli

./build-mac-osx "$VERSION"

exit 0
